config/routes.rb
Rails.application.routes.draw do

  resources :checkins

  resources :attendences

  resources :students

  devise_for :users

  resources :students do

      get 'update'

  end

  get 'signin', to: 'students#signin'

  get 'search', to: 'students#search'

  post 'search', to: 'students#search'

  get 'dash', to: 'students#dash'

  root to: "students#signin"

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :checkins
  belongs_to :checkin

  accepts_nested_attributes_for :checkins


  validates :first_name, :current_rank, presence: true

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :default_url => "50x50>" },   :default_url => 'index_:style.jpg'
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def self.search(search)

  where('first_name LIKE ?', "%#{search}%")

  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]


require 'will_paginate/array'


  # GET /students
  # GET /students.json
  def index
    @students = Student.all.paginate(:page => params[:page], :per_page => 4)
    @student = Student.new


  end

  # GET /students/1
  # GET /students/1.json
  def show

  end



  def signin

    @students = Student.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 4)

  end


  def dash
    @students = Student.all

  end

  # GET /students/new
  def new
    @student = Student.new

  end

def attendance
  @students = Student.all
end


  # GET /students/1/edit
  def edit

  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    @student.checkins.build

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }

      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:avatar, :first_name, :last_name, :current_rank, :start_date, :attendence, checkins_attributes:[:day])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student,:url => students_path, :html => { :multipart => true } do |f| %>
    <% if @student.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>
          <ul>
            <% @student.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="control-group">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :current_rank %><br>
      <%= f.text_field :current_rank %>
    </div>
    <div class="field">
      <%= f.label :start_date %><br>
      <%= f.date_select :start_date %>
    </div>

    <div class="field">
      <%= f.file_field :avatar %>
    </div>

    <br>
    <div class="form-actions2">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  students_path, :class => 'btn' %>
    </div>
<% end %>

app/views/students/attendance.html.erb
<h1>Attendence student</h1>

app/views/students/dash.html.erb
<h1>Stats</h1>

<br>
<br>
<div id="annual"></div>

app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:current_rank) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= image_tag student.avatar.url(:thumb) %></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.current_rank %></td>
        <td><%= student.start_date %></td>

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>

<%= will_paginate @students %>

app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @student.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @student.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_rank) %>:</strong></dt>
  <dd><%= @student.current_rank %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @student.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attendence) %>:</strong></dt>
  <dd><%= @student.attendence %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @student.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @student.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @student.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @student.avatar_updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              students_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_student_path(@student), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              student_path(@student),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/students/signin.html.erb
<h1>Listing students</h1>

<br>

<form>
  <%= form_tag(signin_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Shitheads" %> <br>
      <%= submit_tag "Search" %>
  <% end %>
</form>


<table class="table table-striped">
  <thead>
  <tr>
      <th></th>
      <th>First name</th>
      <th>Last name</th>
      <th>Attendence</th>
  </tr>
  </thead>
  <tbody>


    <% @students.each do |student| %>

      <% onedaylater =  student.checkins.last.created_at.to_date + 1 %>
      <% now =  Time.now %>

      <tr>
        <td> <%= image_tag student.avatar.url(:thumb) %> </td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <% if now < onedaylater %>
        <div class="submit_id">
        <td><%= button_to 'sign-in', checkins_path, method: :post, :params => {"checkin[student_id]" => student.id }, :class => 'btn btn-mini btn-danger test1 ' %></td>
        </div>
        <% else %>
        <div class="submit_id">
          <td><%= button_to 'sign-in', checkins_path, method: :post, :params => {"checkin[student_id]" => student.id }, :class => 'btn btn-mini btn-danger' %></td>
        </div>
        <% end %>
        <td><%= student.checkins.count    %></td>
      </tr>
  <% end %>





  </tbody>
</table>

<br>

<%= will_paginate @students %>