config/routes.rb
Rails.application.routes.draw do

  resources :checkins

  resources :attendences

  resources :students

  devise_for :users

  resources :students do

      get 'update'

  end

  get 'signin', to: 'students#signin'

  get 'search', to: 'students#search'

  post 'search', to: 'students#search'

  get 'dash', to: 'students#dash'

  root to: "students#signin"

end

app/models/attendence.rb
class Attendence < ActiveRecord::Base
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController
  before_action :set_attendence, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @attendences = Attendence.all
    respond_with(@attendences)
  end

  def show
    respond_with(@attendence)
  end

  def new
    @attendence = Attendence.new
    respond_with(@attendence)
  end

  def edit
  end

  def create
    @attendence = Attendence.new(attendence_params)
    @attendence.save
    respond_with(@attendence)
  end

  def update
    @attendence.update(attendence_params)
    respond_with(@attendence)
  end

  def destroy
    @attendence.destroy
    respond_with(@attendence)
  end

  private
    def set_attendence
      @attendence = Attendence.find(params[:id])
    end

    def attendence_params
      params.require(:attendence).permit(:signin)
    end
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/views/attendences/_form.html.erb
<%= form_for(@attendence) do |f| %>
  <% if @attendence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendence.errors.count, "error") %> prohibited this attendence from being saved:</h2>

      <ul>
      <% @attendence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :signin %><br>
    <%= f.number_field :signin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendences/edit.html.erb
<h1>Editing attendence</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendence %> |
<%= link_to 'Back', attendences_path %>

app/views/attendences/index.html.erb
<h1>Listing attendences</h1>

<table>
  <thead>
    <tr>
      <th>Signin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendences.each do |attendence| %>
      <tr>
        <td><%= attendence.signin %></td>
        <td><%= link_to 'Show', attendence %></td>
        <td><%= link_to 'Edit', edit_attendence_path(attendence) %></td>
        <td><%= link_to 'Destroy', attendence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendence', new_attendence_path %>

app/views/attendences/new.html.erb
<h1>New attendence</h1>

<%= render 'form' %>

<%= link_to 'Back', attendences_path %>

app/views/attendences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Signin:</strong>
  <%= @attendence.signin %>
</p>

<%= link_to 'Edit', edit_attendence_path(@attendence) %> |
<%= link_to 'Back', attendences_path %>