config/routes.rb
Rails.application.routes.draw do

  resources :checkins

  resources :attendences

  resources :students

  devise_for :users

  resources :students do

      get 'update'

  end

  get 'signin', to: 'students#signin'

  get 'search', to: 'students#search'

  post 'search', to: 'students#search'

  get 'dash', to: 'students#dash'

  root to: "students#signin"

end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  belongs_to :student
  has_many :students

  accepts_nested_attributes_for :students
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  before_action :set_checkin, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @checkins = Checkin.all
    respond_with(@checkins)
  end

  def show
    respond_with(@checkin)
  end

  def new
    @checkin = Checkin.new
    respond_with(@checkin)

  end

  def edit
  end

  def create
    @checkin = Checkin.new(checkin_params)

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to "http://localhost:3000/signin", notice: 'Student was successfully checked-in.' }
        format.json { render :show, status: :created, location: @checkin}
      else
        format.html { render :new }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @checkin.update(checkin_params)
    respond_with(@checkin)
  end

  def destroy
    @checkin.destroy
    respond_with(@checkin)
  end

  private
    def set_checkin
      @checkin = Checkin.find(params[:id])
    end

    def checkin_params
      params.require(:checkin).permit(:student_id, :day)
    end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= form_for(@checkin) do |f| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% @checkin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>

    <div class="field">
      <%= f.label :day %><br>
      <%= f.check_box :day %>
    </div>


    <%= f.fields_for :students do |x| %>

        <div class="field">
          <%= x.label :first_name %><br>
          <%= x.text_field :first_name %>
        </div>
    <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/checkins/edit.html.erb
<h1>Editing checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<h1>Listing checkins</h1>



<div id="annual"></div>




<table>
  <thead>
    <tr>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checkins.each do |checkin| %>
      <tr>
        <td><%= checkin.student_id %></td>
        <td><%= link_to 'Show', checkin %></td>
        <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
        <td><%= link_to 'Destroy', checkin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New checkin</h1>

<%= render 'form' %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @checkin.student_id %>
</p>

<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>