config/routes.rb
Rails.application.routes.draw do

  resources :checkins

  resources :attendences

  resources :students

  devise_for :users

  resources :students do

      get 'update'

  end

  get 'signin', to: 'students#signin'

  get 'search', to: 'students#search'

  post 'search', to: 'students#search'

  get 'dash', to: 'students#dash'

  root to: "students#signin"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="">Team Bamboo</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "New Students", new_student_path %></li>
          <li><%= link_to "Browse Students", students_path %></li>
          <li><%= link_to "Attendence", signin_path %></li>
          <li><%= link_to "Class Stats", dash_path %></li>
          <li><%= link_to "Ninja Shitss" %></li>

        </ul>

       <ul class="right">
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <% if user_signed_in? %>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
              <%  end %>
              <ul class="dropdown-menu" role="menu">
                <% if user_signed_in? %>
                    <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                    <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'%></li>
                    <li> <%= link_to "Add User", new_user_registration_path, :class => 'navbar-link'%></li>
                <% else %>
                    <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                <% end %>

              </ul>
          </ul>
            </li>
          </ul>

      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="span7"><%= yield %></div>
    <div class="span5">

      <br>
      <br>
      <br>
      <br>

      <div class="picture">
      <% if user_signed_in? %>

      <div class="row-fluid">
        <div class="span8">

        </div>
      <div>

      <% else %>
        <img src="/bamboo.jpg" alt="rss feed" height="700" width="200" />
      <% end %>
       </div>
</div>
    </div>
  </div>
</div>
    </div>
</body>
</html>